### ISSUE TITLE
PHP 7: Error on product page with attributes

### ISSUE THREAD

**Issue by V0IDNIL** [Magento-Japan/m2-jplocalize#3]
Magento 2.0.7 on Apache

If I have a product with attributes and I select the Japanese Product Page, then I get the error

`Fatal error: Uncaught TypeError: Argument 1 passed to iterator_to_array() must implement interface Traversable, null given in
 /home/user/public_html/vendor/magento/framework/View/Element/Html/Calendar.php:86 Stack trace: #0 
 /home/user/public_html/vendor/magento/framework/View/Element/Html/Calendar.php(86): iterator_to_array(NULL) #1 
 /home/user/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(657): Magento\Framework\View\Element\Html\Calendar->_toHtml() #2 
 /home/user/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml() #3 
 /home/user/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('html_calendar') #4 
 /home/user/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('html_calendar') #5 
 /home/user/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(501): Magento\Framework\View\Layout->renderEl in 
 /home/user/public_html/vendor/magento/framework/View/Element/Html/Calendar.php on line 86`

This error only occurs when I use PHP7. With PHP 5.6, everything works fine.

**Comment by HirokazuNishi** [comment]
I can't reproduce it. Could you explain more details? (What did you do?) It seems M2 core bug...

**Comment by V0IDNIL** [comment]
I have two languages: en_US and ja_JP.  
I create a configurable product with the attribute Leather Band (革バンド) and the values black/russet/brown (黒・ラッセット・茶色). Then re-index and flush the cache. 
The English product page works fine. But on the Japanese product page I get the error message above. I tried to change the attribute input type (Dropdown/Visual Swatch/Media Image) but the error remains.

PHP Version is 7.0.6.
Do you need me to supply more information?

**Comment by HirokazuNishi** [comment]
What is your OS? It seems ICU related bug.

**Comment by V0IDNIL** [comment]
CentOS

**Comment by HirokazuNishi** [comment]
I couldn't reproduce but similar issue is already reported on m2 repo. https://github.com/magento/magento2/issues/3541

This issue is related on calendar block and Intl ext. Please check your PHP configuration & Magento cache, di, generation status.

**Comment by V0IDNIL** [comment]
Thank you. I am going to look into it.
