### ISSUE TITLE
Cannot update region id.

### ISSUE THREAD

**Issue by k-fukui** [Magento-Japan/m2-jplocalize#5]
Register and update address cannot set region id from frontend.

customer_address_entity region_id = 0 but region = '大阪府'.

**Comment by HirokazuNishi** [comment]
Could not reproduce. Could you try again with latest codes & 2.0.7 or 2.1.0?

**Comment by k-fukui** [comment]
I'm very sorry.
It was re-made again built 2.1.0 environment, then no longer reproduce.

This issue has already resolved.
