### ISSUE TITLE
Can't install/ インストールできない。

### ISSUE THREAD

**Issue by justanewbie00** [Magento-Japan/m2-jplocalize#7]
I followed the installation manual but there was error:

> Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
> The following modules are outdated:
> Veriteworks_Kana schema: current version - none, required version - 1.0.4
> Veriteworks_Kana data: current version - none, required version - 1.0.4
> 

And the module is not showing in the `setup_module `table in the database. Please help.

**Comment by HirokazuNishi** [comment]
Probably you didn't execute the command that Magento CLI mentioned. It's not bug. It's just you forgot to execute migration command.
