### ISSUE TITLE
Help Installation

### ISSUE THREAD

**Issue by justanewbie00** [Magento-Japan/m2-jplocalize#8]
I'm a bit confused in the installation.

This error shows up when I do the following:

 1. DL and paste the zip file of this under DIR>vendor>magento-japan folder

 2. Run the following command:
    composer config repositories.veriteworksartifacts artifact <Magento2 directory>\vendor\magento-japan
    composer require magento-japan/m2-jplocalize
    php bin/magento setup:upgrade

 3. Then this error shows up:
    Module 'Veriteworks_Region' from '<DIR>\vendor\magento-japan\m2-jplocalize/region' has been already defined in '<DIR>/vendor/veriteworks/m2-region'.

Where did I go wrong? Can you please help me. I'm a newbie in magento and still don't know the way around.

**Comment by HirokazuNishi** [comment]
You completely misunderstood.
This repository is not same as archived version modules. This is development & for developers repository. If you're not familiar with M2 architecture and composer, please use zip archived version from our website.
